# Generated by Django 5.2.3 on 2025-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.CharField(blank=True, help_text='Emoji ou icône du projet', max_length=10)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tech', models.JSONField(blank=True, default=list, help_text='Liste des technologies utilisées')),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('idea', 'Idée'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Projet mis en avant')),
            ],
        ),
    ]
