# Generated by Django 5.2.3 on 2025-06-30 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text="Résumé de l'article")),
                ('content', models.TextField(blank=True, help_text='Contenu en markdown')),
                ('date', models.DateField(auto_now_add=True, help_text='Date de publication')),
                ('readTime', models.CharField(blank=True, help_text="Temps de lecture formaté, ex: '12 min'", max_length=32)),
                ('tags', models.CharField(blank=True, help_text='Liste de tags séparés par des virgules', max_length=255)),
                ('views', models.PositiveIntegerField(default=0, help_text="Nombre de vues de l'article")),
                ('featured', models.BooleanField(default=False, help_text='Article mis en avant')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Durée de lecture en minutes', null=True)),
                ('published', models.BooleanField(default=False, help_text="L'article est-il publié ? (sinon, il est en brouillon)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, help_text="Auteur de l'article", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
