# Generated by Django 5.2.3 on 2025-06-26 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_excerpt_date_readtime_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date de publication'),
            preserve_default=False,
        ),
    ]
